### PR TITLE
Window arrangement support

### PR DESCRIPTION
**Pull request by rgeens**
I've spent some time comparing the Glk spec with the current Twisty implementation and have a rough idea now of what still needs to be done. As a first milestone I want to get games that have a text grid status window working.

The window arrangement code was in a bit of an unfortunate state. There was a mostly complete implementation in roboglk, but it was deleted as part of a refactoring that was left unfinished. I've analyzed and tested both the original implementation and the refactoring to figure out what the issues were and how to proceed from there.

The state of the original:
- Based on AbsoluteLayout, which is deprecated
- Various bugs
- Structure is a bit confusing in places
- Mostly complete

What the refactoring did:
- Deleted all windownode related and pretty much all window arrangement code
- Deleted most interfaces and abstract classes in the window hierarchy. In my opinion this muddies the difference between which functionality is supposed to be not implemented because of the window type and which is simply not implemented yet
- Replaced several integer constants with singleton objects

Let me know if I misinterpreted something. Because the original was mostly complete, because I'm ok with its architecture and because the rest of the changes in the refactoring are mostly cosmetic in my opinion, I decided to reverse-merge the refactoring. I found and fixed the following issues in the original:

- The layout didn't update if the keyboard was closed / opened
- The layout didn't update correctly when adding and closing multiple windows. A WindowNode has a firstChild and secondChild to indicate its children. There was also a keyNode and an otherNode, which referred to respectively the node containing the key window and the firstChild/secondChild that didn't contain the key window. The code got these two pairs of nodes confused. And if a key window was closed the parents wouldn't update correctly. I ended up removing the keyNode and otherNode because they weren't needed anymore.

To test the behaviour I extended windowtest.ulx to support multiple windows. I just opened a pull request for that: https://github.com/erkyrath/glk-dev/pull/8

I also used Kerkerkruip as a test case because it uses many windows and covers a lot of Glk. I didn't include it in the app because of its 20 meg size. I fixed the issues I encountered while attempting to get it to run:

- After cancelling a timer, it wouldn't be recreated, resulting in a crash on the next scheduling attempt
- git crashed on ARM but not on x86. This was due to glk_fileref_create_by_name in glkjni evaluating an uninitialized pointer.
- Implemented namedFile because Kerkerkruip needed it to start
- Return the current skeleton text grid implementation when a text grid is requested. Currently results in an empty window. It's also possible to hack-replace it with a text buffer, but that didn't seem very useful

With that, Kerkerkruip looks like this: https://www.dropbox.com/s/rwxci3ci5nnytqf/kerkerkruip_layout.png?dl=0 . Still a lot of issues, but window arrangement looks ok.

For the windowtest tests I used the examples from sections 3.1, 3.2 and 3.3 in the Glk spec.

### CODE REVIEW

**Comment by curiousdannii** [comment]
Is it returning the wrong window sizes? Kerkerkruip should detect the screen is too narrow and not add the side panels on a screen that size.

**Comment by rgeens** [comment]
No, I used the panels command to get that effect. By default it reports the screen is too small and doesn't show them.

**Comment by sussman** [comment]
Thanks, Raf!  Glad to see you pushing forward on RoboGLK, so we can make it
into a legitimate Android GLK implementation!  Sorry for the delay -- I've
merged your code.  Would you like direct push permission, so you don't need
to submit pull requests anymore?

**Comment by rgeens** [comment]
You're welcome :-) Push permission would indeed be nice. I think for bigger changes I'll stick to my current approach of feature branches on my fork, but that would allow me to merge them myself when finished and also to push small unrelated fixes sooner. Would you like me to send an email to the twisty-dev list for every push or is Github already set up to do that?

**Comment by rgeens** [comment]
Hmm, are you sure that granting the push permission is possible? If I'm reading the [documentation](https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account) correctly it looks like that's not allowed for public Github projects.

> Note: Collaborators can only have push access to a private repository owned by a user account. Push access includes write and read permissions.

**Pull request merged**
